export default {
  fa: [
    'fa fa-user-o',
    'fa fa-key',
    'fa fa-envelope-o',
    'fa fa-power-off',
    'fa fa-gift',
    'fa fa-user',
    'fa fa-calendar',
    'fa fa-list',
    'fa fa-star',
    'fa fa-circle',
  ],
  typcn: [
    'typcn typcn-user-outline',
    'typcn typcn-key',
    'typcn typcn-mail',
    'typcn typcn-power',
    'typcn typcn-gift',
    'typcn typcn-user',
    'typcn typcn-calendar',
    'typcn typcn-th-list',
    'typcn typcn-star',
    'typcn typcn-social-github-circle',
  ],
  mdl: [
    'md-icon|account_box',
    'md-icon|vpn_key',
    'md-icon|mail_outline',
    'md-icon|power_settings_new',
    'md-icon|card_giftcard',
    'md-icon|account_circle',
    'md-icon|schedule',
    'md-icon|view_list',
    'md-icon|star',
    'md-icon|check_circle',
  ],
  fabric: [
    'ms-Icon ms-Icon--PlayerSettings',
    'ms-Icon ms-Icon--Permissions',
    'ms-Icon ms-Icon--Mail',
    'ms-Icon ms-Icon--OutOfOffice',
    'ms-Icon ms-Icon--GiftCard',
    'ms-Icon ms-Icon--PlayerSettings',
    'ms-Icon ms-Icon--Calendar',
    'ms-Icon ms-Icon--CustomList',
    'ms-Icon ms-Icon--FavoriteStar',
    'ms-Icon ms-Icon--LocationCircle',
  ],
  search: {
    fabric: 'ms-Icon ms-Icon--Search',
    fa: 'fa fa-search',
    typcn: 'typcn typcn-zoom',
    mdl: 'md-icon|search',
  },
};
